-- INSTRUCTIONS:
-- write the SQL to create the artists table with 
-- the following columns:

-- artist_id
-- artist_name
-- birthday
-- birthplace
-- is_alive


-- CREATE TABLE <table name> (
--    column_name data_type  column_constraint,
-- )

CREATE TABLE artists (
  artist_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  artist_name varchar NOT NULL UNIQUE,
  birthday DATE NOT NULL,
  birthplace varchar NOT NULL,
  is_alive BOOL NOT NULL
)